require('dotenv').config();
const express = require('express');
const cors = require('cors');
const app = express();

app.use(cors());
app.use(express.json());

const PORT = process.env.PORT || 3001;

app.post('/api/generate-story', async (req, res) => {
  const { protagonist, past_experience, present_reality, catalyst_event, narrative_format } = req.body;

  const final_prompt = `You are an advanced AI specializing in narrative generation. Create a short, poignant story in the form of a '${narrative_format}' from the perspective of a '${protagonist}'.

The story must detail their memory of a specific past experience: '${past_experience}'.

The memory must:
 * Describe the tastes, textures, and feelings associated with this experience with a sense of wonder, reverence, and authenticity.
 * Contrast this experience with their present-day reality, which is '${present_reality}'. The character should refer to this present as normal.
 * Hint at the major event that caused this shift: '${catalyst_event}'.
 * The tone should be deeply personal and emotional, focusing on themes of memory, authenticity, and what has been lost or gained in the name of progress.`;

  try {
    // Placeholder for the actual API call to the LLM
    // const response = await axios.post('https://api.llmprovider.com/v1/completions',
    //   { prompt: final_prompt },
    //   { headers: { 'Authorization': `Bearer ${process.env.AI_API_KEY}` } }
    // );
    // const story = response.data.choices[0].text;

    const story = "This is a placeholder story generated by the backend. The real story will be generated by an AI.";

    res.json({ story });
  } catch (error) {
    console.error('Error generating story:', error);
    res.status(500).json({ error: 'Failed to generate story' });
  }
});

app.listen(PORT, () => {
  console.log(`Server is running on port ${PORT}`);
});
